### ISSUE TITLE
外网部署的时候 apigateway-host-service 无法启动：Authorization failed! Given policy has not granted.

### ISSUE THREAD

**Issue by YahuiWong** [colinin/abp-vue-admin-element-typescript#153]
使用的docker的启动方式

其他服务启动正常
但是 apigateway-host-service 无法启动：Authorization failed! Given policy has not granted.

其中 apigateway-admin-service的Debug.log文件中可以看到如下
```LOG

   at Microsoft.AspNetCore.Authorization.AbpAuthorizationServiceExtensions.CheckAsync(IAuthorizationService authorizationService, AuthorizationPolicy policy)
   at Volo.Abp.Authorization.MethodInvocationAuthorizationService.CheckAsync(MethodInvocationAuthorizationContext context)
   at Volo.Abp.Authorization.AuthorizationInterceptor.AuthorizeAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at LINGYUN.ApiGateway.Ocelot.GlobalConfigurationController.GetAsync(GlobalGetByAppIdInputDto input)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

我检查了redis中的token
![image](https://user-images.githubusercontent.com/32868945/102078502-fe986d80-3e45-11eb-9b08-0323df0c1fca.png)
这个域名已经做过host可以正常访问的

platform.abppermissiongrants表中数据如下

![image](https://user-images.githubusercontent.com/32868945/102078689-4a4b1700-3e46-11eb-8a1c-db24e25dc263.png)

对比过 https://github.com/colinin/abp-vue-admin-element-typescript/issues/136 的方法 还是没有进展  apigateway-host-service 无法启动 无法启动……

**Comment by colinin** [comment]
我看不了图片，不过建议你检查下token中的issue是否和admin配置的一致，或者你可以admin项目启动调试模式，看看ICurrentClient是否正确识别

abp框架中，用户未登录就会提示Authorization failed! Given policy has not granted. 未授权会提示相应的权限名称

**Comment by colinin** [comment]
如果ICurrentClient没有识别到网关客户端，标识IdentityServer配置不一致

**Comment by YahuiWong** [comment]
现在可以看到图片了吗 
有时候可以启动起来 但是 `apigateway-host`出现 Connection refused
```
2020-12-17 12:45:24 [WRN] [Ocelot.Requester.HttpClientHttpRequester] [1] [33] - requestId: 0HM52H6FNMHU9:00000001, previousRequestId: no previous request id, message: You have ignored all SSL warnings by using DangerousAcceptAnyServerCertificateValidator for this DownstreamRoute, UpstreamPathTemplate: Ocelot.Values.UpstreamPathTemplate, DownstreamPathTemplate: Ocelot.Values.DownstreamPathTemplate
2020-12-17 12:45:24 [ERR] [Ocelot.Provider.Polly.PollyCircuitBreakingDelegatingHandler] [1] [37] - requestId: 0HM52H6FNMHU9:00000001, previousRequestId: no previous request id, message: Error in CircuitBreakingDelegatingHandler.SendAync
System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Polly.Timeout.AsyncTimeoutEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Func`2 timeoutProvider, TimeoutStrategy timeoutStrategy, Func`5 onTimeoutAsync, Boolean continueOnCapturedContext)
   at Polly.Timeout.AsyncTimeoutEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Func`2 timeoutProvider, TimeoutStrategy timeoutStrategy, Func`5 onTimeoutAsync, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass3_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.<>c__DisplayClass8_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.CircuitBreaker.AsyncCircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy innerPolicy)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Ocelot.Provider.Polly.PollyCircuitBreakingDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```
我进入容器中手动访问配置的地址都是可以访问的 有邮件吗 我发您一下这里的docker相关配置文件

**Comment by colinin** [comment]
colin.in@foxmail.com

**Comment by YahuiWong** [comment]
> [colin.in@foxmail.com](mailto:colin.in@foxmail.com)

已经发您邮件了

**Comment by lazyabp** [comment]
本地运行正常，部署到服务器网关就启动不了，这是什么情况啊？

Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module LINGYUN.ApiGateway.ApiGatewayHostModule, LINGYUN.ApiGateway.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: One or more errors occurred. (Authorization failed! Given policy has not granted.). See the inner exception for details.
 ---> System.AggregateException: One or more errors occurred. (Authorization failed! Given policy has not granted.)
 ---> Volo.Abp.Http.Client.AbpRemoteCallException: Authorization failed! Given policy has not granted.
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.ThrowExceptionForResponseAsync(HttpResponseMessage response)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAndGetResultAsync[T](IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.GetResultAsync(Task task, Type resultType)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Ocelot.Configuration.Repository.ApiHttpClientFileConfigurationRepository.Get() in /src/services/apigateway/LINGYUN.ApiGateway.Host/Ocelot/Configuration/Repository/ApiHttpClientFileConfigurationRepository.cs:line 41
   at Ocelot.Extenssions.OcelotMiddlewareExtensions.CreateConfiguration(IApplicationBuilder builder) in /src/services/apigateway/LINGYUN.ApiGateway.Host/Ocelot/Ocelot/Extenssions/OcelotMiddlewareExtensions.cs:line 75
   at Ocelot.Extenssions.OcelotMiddlewareExtensions.UseOcelot(IApplicationBuilder builder, OcelotPipelineConfiguration pipelineConfiguration) in /src/services/apigateway/LINGYUN.ApiGateway.Host/Ocelot/Ocelot/Extenssions/OcelotMiddlewareExtensions.cs:line 35
   at Ocelot.Extenssions.OcelotMiddlewareExtensions.UseOcelot(IApplicationBuilder builder) in /src/services/apigateway/LINGYUN.ApiGateway.Host/Ocelot/Ocelot/Extenssions/OcelotMiddlewareExtensions.cs:line 22
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at LINGYUN.ApiGateway.ApiGatewayHostModule.OnApplicationInitialization(ApplicationInitializationContext context) in /src/services/apigateway/LINGYUN.ApiGateway.Host/ApiGatewayHostModule.cs:line 208
   at Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor.Initialize(ApplicationInitializationContext context, IAbpModule module)
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context)
   --- End of inner exception stack trace ---
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModules()
   at Volo.Abp.AbpApplicationWithExternalServiceProvider.Initialize(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplication(IApplicationBuilder app)
   at LINGYUN.ApiGateway.Startup.Configure(IApplicationBuilder app) in /src/services/apigateway/LINGYUN.ApiGateway.Host/Startup.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at DotNetCore.CAP.CapStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at LINGYUN.ApiGateway.Program.Main(String[] args) in /src/services/apigateway/LINGYUN.ApiGateway.Host/Program.cs:line 26

**Comment by lazyabp** [comment]
找到问题，导入ApiGateway初始数据的时候，没有将API的地址和端口替换成线上地址，替换一下，然后清理redis就可以启动了

**Comment by colinin** [comment]
closed

**Comment by weibinlong** [comment]
> 找到问题，导入ApiGateway初始数据的时候，没有将API的地址和端口替换成线上地址，替换一下，然后清理redis就可以启动了
请问是[ApiGateway].[dbo].[appapigatewayreroute]表的[DownstreamHostAndPorts]字段吗？
我现在也是这个服务在生产环境起不来，头大。。

**Comment by weibinlong** [comment]
> 找到问题，导入ApiGateway初始数据的时候，没有将API的地址和端口替换成线上地址，替换一下，然后清理redis就可以启动了

请问是改[ApiGateway].[dbo].[appapigatewayreroute]表的[DownstreamHostAndPorts]字段吗？ @lazyabp 我也遇到这个服务起来的问题

**Comment by colinin** [comment]
DownstreamHostAndPorts字段只是转发请求的下级地址，我看了好几个人的，网关无法启动大多数都是appsettings.json中的AuthServer配置不正确导致的，你们如果仅仅是测试，可以修改为真实可访问的外部IP，或者修改下前端连接地址通过网关或者nginx来转发



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weibinlong <notifications@github.com&gt;
发送时间: 2021年3月7日 00:58
收件人: colinin/abp-vue-admin-element-typescript <abp-vue-admin-element-typescript@noreply.github.com&gt;
抄送: cKey <colin.in@foxmail.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[colinin/abp-vue-admin-element-typescript] 外网部署的时候 apigateway-host-service 无法启动：Authorization failed! Given policy has not granted. (#153)






找到问题，导入ApiGateway初始数据的时候，没有将API的地址和端口替换成线上地址，替换一下，然后清理redis就可以启动了

请问是改[ApiGateway].[dbo].[appapigatewayreroute]表的[DownstreamHostAndPorts]字段吗？ @lazyabp 我也遇到这个服务起来的问题
