### ISSUE TITLE
运行代码提示这个错误

### ISSUE THREAD

**Issue by GitXieJun** [colinin/abp-vue-admin-element-typescript#179]
![A7081BB5-8CC6-467d-8D45-F0EB134913B9](https://user-images.githubusercontent.com/45811979/104551246-805ffe80-5671-11eb-83e4-809292594917.png)

**Comment by GitXieJun** [comment]
2021-01-14 15:14:22 [INF] [] [1324] [1] - Starting web host.
2021-01-14 15:14:23 [INF] [Hangfire.MySql.MySqlStorage] [1324] [1] - DB tables already exist. Exit install
2021-01-14 15:14:24 [FTL] [] [1324] [1] - Host terminated unexpectedly!
Autofac.Core.Activators.Reflection.NoConstructorsFoundException: No accessible constructors were found for the type 'LINGYUN.Abp.MessageService.Chat.IUserChatFriendRepository'.
   at Volo.Abp.Autofac.AbpAutofacConstructorFinder.GetDefaultPublicConstructors(Type type)
   at Volo.Abp.Autofac.AbpAutofacConstructorFinder.FindConstructors(Type targetType)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ConfigurePipeline(IComponentRegistryServices componentRegistryServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.ComponentRegistration.BuildResolvePipeline(IComponentRegistryServices registryServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.ComponentRegistration.BuildResolvePipeline(IComponentRegistryServices registryServices)
   at Autofac.Core.Registration.ComponentRegistryBuilder.Build()
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Volo.Abp.Autofac.AbpAutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at LINGYUN.Abp.MessageService.Program.Main(String[] args) in C:\个人文件\AbpVnext\aspnet-core\services\messages\LINGYUN.Abp.MessageService.HttpApi.Host\Program.cs:line 26

**Comment by colinin** [comment]
是不是修改了消息服务，没有依赖MessageService.EntityFrameworkCoreModule,或者说你重写了IUserChatFriendRepository仓储，但是访问修饰符不是公共的，或者重写的IUserChatFriendRepository仓储没有注入

**Comment by GitXieJun** [comment]
拉取没有做过任何变更运行起来就是这样了

**Comment by GitXieJun** [comment]
我看到abpvnext文档中是这么写的，这个是有什么区别吗
![QQ图片20210117152217](https://user-images.githubusercontent.com/45811979/104834034-cddda500-58d7-11eb-9963-0424a7e69753.png)
![QQ图片20210117152339](https://user-images.githubusercontent.com/45811979/104834057-fcf41680-58d7-11eb-91f1-c87f26962167.png)

**Comment by GitXieJun** [comment]
abpvnext 文档这样写的
context.Services.AddAbpDbContext<BookStoreDbContext>(options =>
{
    options.AddDefaultRepositories();
    options.AddRepository<Book, BookRepository>();
});
项目中这样
  context.Services.AddAbpDbContext<MessageServiceDbContext>(options =>
            {
                options.AddRepository<Notification, INotificationRepository>();
                options.AddRepository<UserNotification, IUserNotificationRepository>();
                options.AddRepository<UserSubscribe, IUserSubscribeRepository>();

                options.AddRepository<ChatGroup, IGroupRepository>();
                options.AddRepository<UserChatGroup, IUserChatGroupRepository>();
                options.AddRepository<UserChatCard, IUserChatCardRepository>();
                options.AddRepository<UserChatSetting, IUserChatSettingRepository>();

                options.AddRepository<UserChatFriend, IUserChatFriendRepository>();

                options.AddDefaultRepositories(includeAllEntities: true);
            });
2者是有区别吗，为什么我改成了  options.AddRepository<UserChatFriend,EfCoreUserChatFriendRepository>();就不再提示报错了

**Comment by colinin** [comment]
没区别，注册接口的话可以替换接口，注册为仓储实现就只能集成实现重写了

**Comment by colinin** [comment]
好的，这个问题先记下，我有时间了写个单元测试看看

**Comment by colinin** [comment]
我未能在本地复现这个问题，你能提供当时的环境信息吗

**Comment by colinin** [comment]
升级框架发现了这个问题，现在是需要通过实现来注册接口的实现，不能再提供一个接口的方式注册仓储了

**Comment by colinin** [comment]
#189 已在此次提交中修复
