### ISSUE TITLE
在 ../Server/account\AuthServer.Host/ 执行 dotnet run 时 报错，缺少字段

### ISSUE THREAD

**Issue by AjuPrince** [colinin/abp-vue-admin-element-typescript#196]
---
FROM (
    SELECT `i`.`Id`, `i`.`AllowedAccessTokenSigningAlgorithms`, `i`.`ConcurrencyStamp`, `i`.`CreationTime`, `i`.`CreatorId`, `i`.`DeleterId`, `i`.`DeletionTime`, `i`.`Description`, `i`.`DisplayName`, `i`.`Enabled`, `i`.`ExtraProperties`, `i`.`IsDeleted`, `i`.`LastModificationTime`, `i`.`LastModifierId`, `i`.`Name`, `i`.`ShowInDiscoveryDocument`
    FROM `IdentityServerApiResources` AS `i`
    WHERE (@__ef_filter__p_0 OR NOT (`i`.`IsDeleted`)) AND (`i`.`Name` = @__apiResourceName_0)
    ORDER BY `i`.`Id`
    LIMIT 1
) AS `t`
ORDER BY `t`.`Id`
2021-02-04 15:08:40 [ERR] [Microsoft.EntityFrameworkCore.Query] [15384] [12] - An exception occurred while iterating over the results of a query for context type 'Volo.Abp.IdentityServer.EntityFrameworkCore.IdentityServerDbContext'.
MySqlConnector.MySqlException (0x80004005): Unknown column 'i.AllowedAccessTokenSigningAlgorithms' in 'field list'
---
执行  dotnet ef migrations add "Update_Data_Structure" 后 再次执行 dotnet ef database update 后，报错，错误信息：
Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `IdentityServerApiScopeClaims` DROP FOREIGN KEY `FK_IdentityServerApiScopeClaims_IdentityServerApiScopes_ApiScop~`;
MySqlConnector.MySqlException (0x80004005): Can't DROP 'FK_IdentityServerApiScopeClaims_IdentityServerApiScopes_ApiScop~'; check that column/key exists
 ---> MySqlConnector.MySqlException (0x80004005): Can't DROP 'FK_IdentityServerApiScopeClaims_IdentityServerApiScopes_ApiScop~'; check that column/key exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 118
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 436
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 264
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 100
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

**Comment by OldKing-lion** [comment]
> ## FROM (
> SELECT `i`.`Id`, `i`.`AllowedAccessTokenSigningAlgorithms`, `i`.`ConcurrencyStamp`, `i`.`CreationTime`, `i`.`CreatorId`, `i`.`DeleterId`, `i`.`DeletionTime`, `i`.`Description`, `i`.`DisplayName`, `i`.`Enabled`, `i`.`ExtraProperties`, `i`.`IsDeleted`, `i`.`LastModificationTime`, `i`.`LastModifierId`, `i`.`Name`, `i`.`ShowInDiscoveryDocument`
> FROM `IdentityServerApiResources` AS `i`
> WHERE (@__ef_filter__p_0 OR NOT (`i`.`IsDeleted`)) AND (`i`.`Name` = @__apiResourceName_0)
> ORDER BY `i`.`Id`
> LIMIT 1
> ) AS `t`
> ORDER BY `t`.`Id`
> 2021-02-04 15:08:40 [ERR] [Microsoft.EntityFrameworkCore.Query] [15384] [12] - An exception occurred while iterating over the results of a query for context type 'Volo.Abp.IdentityServer.EntityFrameworkCore.IdentityServerDbContext'.
> MySqlConnector.MySqlException (0x80004005): Unknown column 'i.AllowedAccessTokenSigningAlgorithms' in 'field list'
> 执行 dotnet ef migrations add "Update_Data_Structure" 后 再次执行 dotnet ef database update 后，报错，错误信息：
> Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
> ALTER TABLE `IdentityServerApiScopeClaims` DROP FOREIGN KEY `FK_IdentityServerApiScopeClaims_IdentityServerApiScopes_ApiScop~`;
> MySqlConnector.MySqlException (0x80004005): Can't DROP 'FK_IdentityServerApiScopeClaims_IdentityServerApiScopes_ApiScop~'; check that column/key exists
> ---> MySqlConnector.MySqlException (0x80004005): Can't DROP 'FK_IdentityServerApiScopeClaims_IdentityServerApiScopes_ApiScop~'; check that column/key exists
> at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49 at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 118
> at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 436 at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60 at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 264
> at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 100
> at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
> at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues) at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
> at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
> at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
> at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
> at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
> at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

我是没遇到这个问题，但是identity结构迁移要自己删改一下字段，Identity升级了，会报错。但是有个大问题，我环境都没问题了，运行起来后还是没有办法完整跑起来，前端直接500

**Comment by colinin** [comment]
这个脚本是用于在SQL工具中手动执行的，不能使用EF工具，IdentityServer官方也给过提示

**Comment by AjuPrince** [comment]
感谢回复，我稍后尝试下！
