### ISSUE TITLE
执行build-aspnetcore-ef-update.ps1时报错

### ISSUE THREAD

**Issue by seamusic** [colinin/abp-vue-admin-element-typescript#236]
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> MySqlConnector.MySqlException (0x80004005): Access denied for user 'colin'@'10.42.220.39' (using password: YES)
   at MySqlConnector.Core.ServerSession.SwitchAuthenticationAsync(ConnectionSettings cs, PayloadData payload, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 577
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 467
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 110
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 140
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 846
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 410
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 376
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at LINGYUN.Platform.EntityFrameworkCore.PlatformHttpApiHostMigrationsDbContextFactory.CreateDbContext(String[] args) in E:\source\net\abp\abpvue\aspnet-core\services\platform\LINGYUN.Platform.HttpApi.Host\EntityFrameworkCore\PlatformHttpApiHostMigrationsDbContextFactory.cs:line 15`

不知道哪里冒出来的  'colin'@'10.42.220.39' 全文搜索也找不着，是在打包的dll里？

**Comment by seamusic** [comment]
有个配置文件的LINGYUN.Platform.HttpApi.Host/appsettings.Development.json的用户名为User Id=colin;导致没有替换导致的。

**Comment by colinin** [comment]
配置文件已改为root账户，请自行变更中间件及数据库连接字符串，只在第一次克隆仓库时才需要手动处理配置文件
