### ISSUE TITLE
abp- 后台也运行不起来

### ISSUE THREAD

**Issue by zqhgit001** [colinin/abp-vue-admin-element-typescript#300]
D:\abpvue\abp\aspnet-core\services\admin\LINGYUN.Abp.BackendAdmin.HttpApi.Host
 我只启动这个项目也运行不起来，日志：
2021-09-14 11:11:03 [DBG] [DotNetCore.CAP.Internal.Bootstrapper] [9700] [1] - ### CAP background task is starting.
2021-09-14 11:11:05 [DBG] [DotNetCore.CAP.RabbitMQ.ConnectionChannelPool] [9700] [1] - RabbitMQ configuration:'HostName:Your RabbitMQ server connection address, Port:5672, UserName:Your RabbitMQ server connection user, Password:Your RabbitMQ server connection user password, ExchangeName:The name of your RabbitMQ server switch'
2021-09-14 11:11:24 [ERR] [DotNetCore.CAP.Internal.Bootstrapper] [9700] [1] - Initializing the storage structure failed!
MySqlConnector.MySqlException (0x80004005): Connect Timeout expired.
 ---> MySqlConnector.MySqlException (0x80004005): Unknown database 'platform'
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 498
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 376
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 107
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 137
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 873
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 895
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 414
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 380
   at DotNetCore.CAP.MySql.DbConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String sql, IDbTransaction transaction, Object[] sqlParams)
   at DotNetCore.CAP.MySql.MySqlStorageInitializer.InitializeAsync(CancellationToken cancellationToken)
   at DotNetCore.CAP.MySql.MySqlStorageInitializer.InitializeAsync(CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.Bootstrapper.BootstrapAsync()
2021-09-14 11:11:30 [ERR] [DotNetCore.CAP.Internal.Bootstrapper] [9700] [1] - Starting the processors throw an exception.
DotNetCore.CAP.BrokerConnectionException: Broker Unreachable
 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> System.AggregateException: One or more errors occurred. (Connection failed)
 ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed
 ---> System.Net.Sockets.SocketException (11001): 不知道这样的主机。

**Comment by colinin** [comment]
请检查**LINGYUN.Abp.BackendAdmin.HttpApi.Host**项目**appsettings.json**中CAP=>RabbitMQ连接信息

**Comment by colinin** [comment]
这是很基本的RabbitMQ无法连接造成CAP无法启动的问题，要学会分析日志

**Comment by zqhgit001** [comment]
老铁，还是不行啊，配置文件：   "CAP": {
    "EventBus": {
      "DefaultGroupName": "BackendAdmin",
      "Version": "v1",
      "FailedRetryInterval": 300,
      "FailedRetryCount": 10
    },
    "RabbitMQ": {
      "HostName": "localhost",
      "Port": 15672,
      "UserName": "guest",
      "Password": "guest",
      "ExchangeName": "MsDemo",
      "VirtualHost": "/"
    }
  },
错误日志：
2021-09-16 14:23:12 [DBG] [DotNetCore.CAP.Internal.Bootstrapper] [18952] [1] - ### CAP background task is starting.
2021-09-16 14:23:12 [DBG] [DotNetCore.CAP.RabbitMQ.ConnectionChannelPool] [18952] [1] - RabbitMQ configuration:'HostName:localhost, Port:15672, UserName:guest, Password:guest, ExchangeName:MsDemo'
2021-09-16 14:23:12 [DBG] [DotNetCore.CAP.MySql.MySqlStorageInitializer] [18952] [1] - Ensuring all create database tables script are applied.
2021-09-16 14:23:19 [ERR] [DotNetCore.CAP.Internal.Bootstrapper] [18952] [1] - Starting the processors throw an exception.
DotNetCore.CAP.BrokerConnectionException: Broker Unreachable
 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> System.IO.IOException: connection.start was never received, likely due to a network timeout
   at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection()
   at DotNetCore.CAP.RabbitMQ.ConnectionChannelPool.<>c__DisplayClass19_0.<CreateConnection>b__1()
   at DotNetCore.CAP.RabbitMQ.ConnectionChannelPool.GetConnection()
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.Connect()
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClientFactory.Create(String groupId)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClientFactory.Create(String groupId)
   at DotNetCore.CAP.Internal.ConsumerRegister.Execute()
   at DotNetCore.CAP.Internal.ConsumerRegister.Start(CancellationToken stoppingToken)

**Comment by colinin** [comment]
&nbsp;RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable


已经告诉你端点不可达了，你先按照RabbitMQ文档部署好再说




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 下午2:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [colinin/abp-vue-admin-element-typescript] abp- 后台也运行不起来 (#300)





 
老铁，还是不行啊，配置文件：   "CAP": {
 "EventBus": {
 "DefaultGroupName": "BackendAdmin",
 "Version": "v1",
 "FailedRetryInterval": 300,
 "FailedRetryCount": 10
 },
 "RabbitMQ": {
 "HostName": "localhost",
 "Port": 15672,
 "UserName": "guest",
 "Password": "guest",
 "ExchangeName": "MsDemo",
 "VirtualHost": "/"
 }
 },
 错误日志：
 2021-09-16 14:23:12 [DBG] [DotNetCore.CAP.Internal.Bootstrapper] [18952] [1] - ### CAP background task is starting.
 2021-09-16 14:23:12 [DBG] [DotNetCore.CAP.RabbitMQ.ConnectionChannelPool] [18952] [1] - RabbitMQ configuration:'HostName:localhost, Port:15672, UserName:guest, Password:guest, ExchangeName:MsDemo'
 2021-09-16 14:23:12 [DBG] [DotNetCore.CAP.MySql.MySqlStorageInitializer] [18952] [1] - Ensuring all create database tables script are applied.
 2021-09-16 14:23:19 [ERR] [DotNetCore.CAP.Internal.Bootstrapper] [18952] [1] - Starting the processors throw an exception.
 DotNetCore.CAP.BrokerConnectionException: Broker Unreachable
 ---&gt; RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---&gt; System.IO.IOException: connection.start was never received, likely due to a network timeout
 at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
 at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
 at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)
 at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
 at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
 at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
 --- End of inner exception stack trace ---
 at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
 at RabbitMQ.Client.ConnectionFactory.CreateConnection(String clientProvidedName)
 at RabbitMQ.Client.ConnectionFactory.CreateConnection()
 at DotNetCore.CAP.RabbitMQ.ConnectionChannelPool.<&gt;c__DisplayClass19_0.b__1()
 at DotNetCore.CAP.RabbitMQ.ConnectionChannelPool.GetConnection()
 at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.Connect()
 at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClientFactory.Create(String groupId)
 --- End of inner exception stack trace ---
 at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClientFactory.Create(String groupId)
 at DotNetCore.CAP.Internal.ConsumerRegister.Execute()
 at DotNetCore.CAP.Internal.ConsumerRegister.Start(CancellationToken stoppingToken)

**Comment by zqhgit001** [comment]
RabbitMQ  服务我已经启动起来了，http://localhost:15672/#/users   用户名和密码都是guest   端口号是15672，" RabbitMQ": {
"HostName": "localhost",
"Port": 15672,
"UserName": "guest",
"Password": "guest",
"ExchangeName": "MsDemo",
"VirtualHost": "/"   还需要哪里配置？ 我的QQ：68383913  我可以给你发错误图片，劳驾了！

**Comment by colinin** [comment]
部署在Docker容器吗？localhost对应当前主机，哪怕Docker与本机部署在一起也不能用localhost通讯



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 下午2:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [colinin/abp-vue-admin-element-typescript] abp- 后台也运行不起来 (#300)





 
RabbitMQ  服务我已经启动起来了，http://localhost:15672/#/users   用户名和密码都是guest   端口号是15672，" RabbitMQ": {
 "HostName": "localhost",
 "Port": 15672,
 "UserName": "guest",
 "Password": "guest",
 "ExchangeName": "MsDemo",
 "VirtualHost": "/"   还需要哪里配置？ 我的QQ：68383913  我可以给你发错误图片，劳驾了！
 
&mdash;

**Comment by zqhgit001** [comment]
我现在没有部署在Docker容器，只用VS 打开来运行，就运行不起来。是不是必须先要部署在docker下，然后才能运行？我现在想先在VS里运行起来，最后考虑部署的事。

**Comment by colinin** [comment]
那就很明显了，你没有了解RabbitMQ，在使用未知中间件之前，请先查阅文档：https://www.rabbitmq.com/dotnet-api-guide.html






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 下午2:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [colinin/abp-vue-admin-element-typescript] abp- 后台也运行不起来 (#300)





 
我现在没有部署在Docker容器，只用VS 打开来运行，就运行不起来。是不是必须先要部署在docker下，然后才能运行？我现在想先在VS里运行起来，最后考虑部署的事。
 
&mdash;

**Comment by zqhgit001** [comment]
我现在是赶着鸭子上树，现用现学，没有办法，是不是没有docker，在vs里运行不起来？

**Comment by colinin** [comment]
我都截图给你点明了，与你环境无关，你通讯端口写错了，15672是管理插件端口，5672和5671才是通讯端口



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [colinin/abp-vue-admin-element-typescript] abp- 后台也运行不起来 (#300)





 
我现在是赶着鸭子上树，现用现学，没有办法，是不是没有docker，在vs里运行不起来？
 
&mdash;

**Comment by zqhgit001** [comment]
老铁，现在是不是问题转移到了mysql上了？
2021-09-16 15:40:44 [DBG] [Microsoft.EntityFrameworkCore.Query] [15412] [13] - Compiling query expression: 
'DbSet<PermissionGrant>()
    .OrderBy(x => x.Id)
    .FirstOrDefault(s => s.Name == __name_0 && s.ProviderName == __providerName_1 && s.ProviderKey == __providerKey_2)'
2021-09-16 15:40:45 [DBG] [Microsoft.EntityFrameworkCore.Query] [15412] [13] - Generated query execution expression: 
'queryContext => 
{
    queryContext.AddParameter(
        name: "__ef_filter__p_0", 
        value: (object)Invoke(queryContext => Convert(Not(Convert(queryContext.Context, PermissionManagementDbContext).IsMultiTenantFilterEnabled), Object), queryContext)
    );
    queryContext.AddParameter(
        name: "__ef_filter__CurrentTenantId_1", 
        value: (object)Invoke(queryContext => Convert(Convert(queryContext.Context, PermissionManagementDbContext).CurrentTenantId, Object), queryContext)
    );
    return ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<PermissionGrant>(
        asyncEnumerable: new SplitQueryingEnumerable<PermissionGrant>(
            (RelationalQueryContext)queryContext, 
            RelationalCommandCache.SelectExpression(
                Projection Mapping:
                    EmptyProjectionMember -> Dictionary<IProperty, int> { [Property: PermissionGrant.Id (Guid) Required PK AfterSave:Throw, 0], [Property: PermissionGrant.Name (string) Required Index MaxLength(128), 1], [Property: PermissionGrant.ProviderKey (string) Required Index MaxLength(64), 2], [Property: PermissionGrant.ProviderName (string) Required Index MaxLength(64), 3], [Property: PermissionGrant.TenantId (Nullable<Guid>), 4], }
                SELECT TOP(1) a.Id, a.Name, a.ProviderKey, a.ProviderName, a.TenantId
                FROM AbpPermissionGrants AS a
                WHERE (@__ef_filter__p_0 || (a.TenantId == @__ef_filter__CurrentTenantId_1)) && (((a.Name == @__name_0) && (a.ProviderName == @__providerName_1)) && (a.ProviderKey == @__providerKey_2))
                ORDER BY a.Id ASC), 
            Func<QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator, PermissionGrant>, 
            null, 
            null, 
            Volo.Abp.PermissionManagement.EntityFrameworkCore.PermissionManagementDbContext, 
            False, 
            False
        ), 
        cancellationToken: queryContext.CancellationToken);
}'
2021-09-16 15:40:45 [DBG] [Microsoft.EntityFrameworkCore.Database.Command] [15412] [13] - Creating DbCommand for 'ExecuteReader'.
2021-09-16 15:40:45 [DBG] [Microsoft.EntityFrameworkCore.Database.Command] [15412] [13] - Created DbCommand for 'ExecuteReader' (2ms).
2021-09-16 15:40:45 [DBG] [Microsoft.EntityFrameworkCore.Database.Command] [15412] [13] - Executing DbCommand [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__name_0='?' (Size = 128), @__providerName_1='?' (Size = 64), @__providerKey_2='?' (Size = 64)], CommandType='"Text"', CommandTimeout='30']
SELECT `a`.`Id`, `a`.`Name`, `a`.`ProviderKey`, `a`.`ProviderName`, `a`.`TenantId`
FROM `AbpPermissionGrants` AS `a`
WHERE (@__ef_filter__p_0 OR (`a`.`TenantId` IS NULL)) AND (((`a`.`Name` = @__name_0) AND (`a`.`ProviderName` = @__providerName_1)) AND (`a`.`ProviderKey` = @__providerKey_2))
ORDER BY `a`.`Id`
LIMIT 1
2021-09-16 15:40:45 [INF] [Microsoft.EntityFrameworkCore.Database.Command] [15412] [13] - Executed DbCommand (63ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__name_0='?' (Size = 128), @__providerName_1='?' (Size = 64), @__providerKey_2='?' (Size = 64)], CommandType='"Text"', CommandTimeout='30']
SELECT `a`.`Id`, `a`.`Name`, `a`.`ProviderKey`, `a`.`ProviderName`, `a`.`TenantId`
FROM `AbpPermissionGrants` AS `a`
WHERE (@__ef_filter__p_0 OR (`a`.`TenantId` IS NULL)) AND (((`a`.`Name` = @__name_0) AND (`a`.`ProviderName` = @__providerName_1)) AND (`a`.`ProviderKey` = @__providerKey_2))
ORDER BY `a`.`Id`
LIMIT 1

**Comment by zqhgit001** [comment]
老铁，现在是不是mysql初始化数据库表有问题?
2021-09-16 15:40:53 [ERR] [Microsoft.EntityFrameworkCore.Database.Command] [15412] [8] - Failed executing DbCommand (605ms) [Parameters=[@__providerName_0='?' (Size = 64)], CommandType='"Text"', CommandTimeout='30']
SELECT `a`.`Id`, `a`.`Name`, `a`.`ProviderKey`, `a`.`ProviderName`, `a`.`Value`
FROM `AbpSettings` AS `a`
WHERE (`a`.`ProviderName` = @__providerName_0) AND `a`.`ProviderKey` IS NULL
2021-09-16 15:40:54 [ERR] [Microsoft.EntityFrameworkCore.Query] [15412] [8] - An exception occurred while iterating over the results of a query for context type 'Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext'.
MySqlConnector.MySqlException (0x80004005): Table 'platform.abpsettings' doesn't exist
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 890
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 119
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 315
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 307
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
MySqlConnector.MySqlException (0x80004005): Table 'platform.abpsettings' doesn't exist
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 890
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 119
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 315
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 307
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2021-09-16 15:40:57 [FTL] [Microsoft.AspNetCore.Hosting.Diagnostics] [15412] [1] - Application startup exception

**Comment by zqhgit001** [comment]
老铁，现在情况是数据库中只有Platform数据库，而且下面有4张表，并且表都是空数据

**Comment by colinin** [comment]
EF文档，数据库迁移好好看看



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 晚上6:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [colinin/abp-vue-admin-element-typescript] abp- 后台也运行不起来 (#300)





 
老铁，现在情况是数据库中只有Platform数据库，而且下面有4张表，并且表都是空数据
 
&mdash;

**Comment by zqhgit001** [comment]
老铁，LINGYUN.BackendAdminApp.Host数据库迁移有问题   cd aspnet-core/services/admin/LINGYUN.BackendAdminApp.Host
dotnet ef database update ，  LINGYUN.BackendAdminApp.Host解决方案下有51个项目，是不是还需要在其他地方配置？ EF tools 是5.0.8  提示需要5.0.10  我在项目中就没有找到5.0.8的版本啊

**Comment by colinin** [comment]
大哥，你能好好看文档吗？？？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 晚上6:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [colinin/abp-vue-admin-element-typescript] abp- 后台也运行不起来 (#300)





 
老铁，LINGYUN.BackendAdminApp.Host数据库迁移有问题   cd aspnet-core/services/admin/LINGYUN.BackendAdminApp.Host
 dotnet ef database update ，  LINGYUN.BackendAdminApp.Host解决方案下有51个项目，是不是还需要在其他地方配置？ EF tools 是5.0.8  提示需要5.0.10  我在项目中就没有找到5.0.8的版本啊
 
&mdash;

**Comment by zqhgit001** [comment]
老铁，你写得的文档我看了，但是项目LINGYUN.BackendAdminApp.Host 项目下的包ef tools版本是5.0.10啊 还要在其他哪个项目下要更新版本？

**Comment by zqhgit001** [comment]
老铁，这里我写得内容和显示的内容不一致啊，并且图片也不能发啊，我的QQ：68383913

**Comment by zqhgit001** [comment]
老铁，这里写得内容和显示的内容不一样啊

**Comment by zqhgit001** [comment]
老铁，PM> Update-Database
Build started...
Build succeeded.
Applying migration '20200804085641_Migration-Backend-Admin-MySql'.
Failed executing DbCommand (1,223ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE `AbpPermissionGrants` (
    `Id` char(36) NOT NULL,
    `TenantId` char(36) NULL,
    `Name` varchar(128) NOT NULL,
    `ProviderName` varchar(64) NOT NULL,
    `ProviderKey` varchar(64) NOT NULL,
    CONSTRAINT `PK_AbpPermissionGrants` PRIMARY KEY (`Id`)
);
MySqlConnector.MySqlException (0x80004005): Table 'abppermissiongrants' already exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 266
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 101
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Table 'abppermissiongrants' already exists
