### ISSUE TITLE
How to start to debug with backend application

### ISSUE THREAD

**Issue by GerryGe** [colinin/abp-vue-admin-element-typescript#34]
Hi, can you detail how to start the backend application?

**Comment by NiceLisan** [comment]
yeah, it's   real frustrated now. 
can you share the whole sln project structure that can be compiled without any error.
currently each project is missing the correct appsettings.Development.json; although you supplied them in the seperated folder.
sincerely thanks

some backend services error looks like this. but i can promise i have set the correct parameters of rabbitmq in the appsetting file.

`[ERR] [DotNetCore.CAP.Internal.ConsumerRegister] [35496] [11] - Broker Unreachable
DotNetCore.CAP.BrokerConnectionException: Broker Unreachable
 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text='NOT_ALLOWED - vhost multi.service.test not found', classId=10, methodId=40
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ConnectionOpen(String virtualHost, String capabilities, Boolean insist)
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(String clientProvidedName)
   at DotNetCore.CAP.RabbitMQ.ConnectionChannelPool.<>c__DisplayClass19_0.<CreateConnection>b__1()
   at DotNetCore.CAP.RabbitMQ.ConnectionChannelPool.GetConnection()
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClient.Connect()
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClientFactory.Create(String groupId)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.RabbitMQ.RabbitMQConsumerClientFactory.Create(String groupId)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass17_0.<Start>b__0()`

**Comment by colinin** [comment]
@NiceLisan 
**RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text='NOT_ALLOWED - vhost multi.service.test not found'**

This error has prompted you. In my RabbitMQ configuration, the VisualHost name is multi-service.test, and you need to change the configuration of your own RabbitMQ server

**Comment by colinin** [comment]
@GerryGe 
After clone the project, you will need to restore **apigateway-init.sql** to your gateway administration database. Then copy the configuration files to the root directory of the service and double-click the **start-all-service.bat** file to move all the background services. Currently, you need to change the connection string and RabbitMQ connection information according to your server configuration

**Comment by colinin** [comment]
@GerryGe 
Launching the error stack will send out, and I'll show you where the configuration went wrong, like the one on the second floor

**Comment by NiceLisan** [comment]
> @NiceLisan
> **RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text='NOT_ALLOWED - vhost multi.service.test not found'**
> 
> This error has prompted you. In my RabbitMQ configuration, the VisualHost name is multi-service.test, and you need to change the configuration of your own RabbitMQ server

in my own practice, the cap rabbit mq WILL create the exchange,queue automaticallly.
in your meaning, i should create the exchange,channel,queue in the rabbitmq server by myself manually way? 
it's hard to imagine that.

and will you provide the sln structure file to help new beginners compile your source projects effectively？

**Comment by NiceLisan** [comment]
> @GerryGe
> After clone the project, you will need to restore **apigateway-init.sql** to your gateway administration database. Then copy the configuration files to the root directory of the service and double-click the **start-all-service.bat** file to move all the background services. Currently, you need to change the connection string and RabbitMQ connection information according to your server configuration

maybe you are wrong. you've missed the database migration job. it's really miserable!!! 
all the service database migration are totally miserable, you didnot write any help tip documets about that. 

maybe lots of someone like me  could not run the source projects successfully. so frustrated!

**Comment by colinin** [comment]
@NiceLisan 
I'm ready to create a series of **Dockerfile** and build the entire service application with **docker-componse**, so stay with me

**Comment by NiceLisan** [comment]
@colinin
thanks, but i'm concerning on how to build  the source project files and run  successfully. it's really appreciated that you can provide one sln file that could be compiled by the vs2019.

**Comment by colinin** [comment]
@NiceLisan 
Even if RabbitMQ is using the default VitualHost, it is essential that you change to the default VitualHost, such as **/**, and that the connection user and password are specified

**Comment by colinin** [comment]
If you do not want to restore the database structure of the gateway, then you can deactivate the management gateway service. I can export an **ocelot.Json** file, but this is not recommended, because you will need to implement the dynamic management of the gateway yourself

**Comment by GerryGe** [comment]
Can you write the detail steps for different scenarios, for example: 
1. Locally debug
2. Docker
For local debug, can you write how to change database connection, migration database and so on...
I totally can not understand you say "you will need to restore apigateway-init.sql to your gateway administration database", do you mean I create a database first then execute your apigateway-init.sql?

**Comment by GerryGe** [comment]
I think the purpose of your open source is to have more people participate in your project, learn from each other, and improve each other. Now the biggest problem, we can't successfully start your project.

**Comment by colinin** [comment]
> 2\. 我完全无法理解您说“您将需要将apigateway-init.sql还原到网关管理数据库”，您的意思是我先创建一个数据库，然后执行您的apigateway-init.sql吗？

**If you have read the documentation, there should be no doubt**
https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations

**Comment by NiceLisan** [comment]
> > 2. 我完全无法理解您说“您将需要将apigateway-init.sql还原到网关管理数据库”，您的意思是我先创建一个数据库，然后执行您的apigateway-init.sql吗？
> 
> **If you have read the documentation, there should be no doubt**
> https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations

actually , we had to create the apigateway database manually, then import the apigateway-init.sql , i tried add the apigateway migration failed. 
sincerely hope you can share the all-projects-in-one sln file that can help us to understand your open source projects.

**Comment by colinin** [comment]
@NiceLisan 

Now that, I've written the gateway initialization script into the seed data, starting the Gateway management project automatically initializes the gateway data, but you need to combine the **EntityFramework documentation** to ensure that the project database is successfully migrated

**Comment by NiceLisan** [comment]
> @NiceLisan
> 
> Now that, I've written the gateway initialization script into the seed data, starting the Gateway management project automatically initializes the gateway data, but you need to combine the **EntityFramework documentation** to ensure that the project database is successfully migrated

now, i've tried again. 
i build the projects successfully; 
i configured the database, rabbitmq successfully.
i seed the database successfully.

but i still encountered the following errors;

1: in the service authserver.host
```
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'platform.abpsettings' doesn't exist
[DotNetCore.CAP.Internal.ConsumerRegister] [34180] [20] - Broker Unreachable
DotNetCore.CAP.BrokerConnectionException: Broker Unreachable
 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text='NOT_ALLOWED - vhost multi.service.test not found', classId=10, methodId=40
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
```

2: in the service \LINGYUN.ApiGateway.HttpApi.Host
`MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'platform.abppermissiongrants' doesn't exist`

3: in the service admin\LINGYUN.BackendAdminApp.Host
```
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'platform.abppermissiongrants' doesn't exist
 [DotNetCore.CAP.Internal.ConsumerRegister] [19620] [10] - Broker Unreachable
DotNetCore.CAP.BrokerConnectionException: Broker Unreachable
 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text='NOT_ALLOWED - vhost multi.service.test not found', classId=10, methodId=40
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
```

4: in the service messages\LINGYUN.Abp.MessageService.HttpApi.Host
```
[ERR] [DotNetCore.CAP.Internal.ConsumerRegister] [31940] [12] - Broker Unreachable
DotNetCore.CAP.BrokerConnectionException: Broker Unreachable
 ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=530, text='NOT_ALLOWED - vhost multi.service.test not found', classId=10, methodId=40
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
```

5: in the service platform\LINGYUN.Platform.HttpApi.Host;
it's the only lucky one , i can run without any errors.

can you help me to figure out what the hell mistakes had blocked me. sincerely thanks.

**Comment by NiceLisan** [comment]
while i tried to add the two table  `Table 'platform.abpsettings','platform.abppermissiongrants'` manually , now the service 1,3,4,5
can run successfully. but the service apigateway still has the following fatal errors:

 ```
 [FTL] [Microsoft.AspNetCore.Hosting.Diagnostics] [30004] [1] - Application startup exception
Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module LINGYUN.ApiGateway.ApiGatewayHostModule, LINGYUN.ApiGateway.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: One or more errors occurred. (Remote service returns error! StatusCode = InternalServerError). See the inner exception for details.
 ---> System.AggregateException: One or more errors occurred. (Remote service returns error! StatusCode = InternalServerError)
 ---> Volo.Abp.AbpException: Remote service returns error! StatusCode = InternalServerError
   at Volo.Abp.Http.Client.DynamicProxying.ApiDescriptionFinder.GetApiDescriptionFromServerAsync(HttpClient client, String baseUrl)
   at Volo.Abp.Http.Client.DynamicProxying.ApiDescriptionCache.GetAsync(String baseUrl, Func`1 factory)
   at Volo.Abp.Http.Client.DynamicProxying.ApiDescriptionFinder.GetApiDescriptionAsync(HttpClient client, String baseUrl)
   at Volo.Abp.Http.Client.DynamicProxying.ApiDescriptionFinder.FindActionAsync(HttpClient client, String baseUrl, Type serviceType, MethodInfo method)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAndGetResultAsync[T](IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.GetResultAsync(Task task, Type resultType)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Ocelot.Configuration.Repository.ApiHttpClientFileConfigurationRepository.Get() in E:\abp-vue-admin-element-typescript\aspnet-core\services\apigateway\LINGYUN.ApiGateway.Host\Ocelot\Configuration\Repository\ApiHttpClientFileConfigurationRepository.cs:line 41
   at Ocelot.Extenssions.OcelotMiddlewareExtensions.CreateConfiguration(IApplicationBuilder builder) in E:\abp-vue-admin-element-typescript\aspnet-core\services\apigateway\LINGYUN.ApiGateway.Host\Ocelot\Ocelot\Extenssions\OcelotMiddlewareExtensions.cs:line 75
   at Ocelot.Extenssions.OcelotMiddlewareExtensions.UseOcelot(IApplicationBuilder builder, OcelotPipelineConfiguration pipelineConfiguration) in E:\abp-vue-admin-element-typescript\aspnet-core\services\apigateway\LINGYUN.ApiGateway.Host\Ocelot\Ocelot\Extenssions\OcelotMiddlewareExtensions.cs:line 35
   at Ocelot.Extenssions.OcelotMiddlewareExtensions.UseOcelot(IApp
```
and 

```
[FTL] [Microsoft.AspNetCore.Hosting.Diagnostics] [31784] [1] - Application startup exception
Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module LINGYUN.ApiGateway.ApiGatewayHttpApiHostModule, LINGYUN.ApiGateway.HttpApi.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: Failed to read the result set.. See the inner exception for details.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Failed to read the result set.
 ---> System.ArgumentOutOfRangeException: delay must not be negative: -63 (Parameter 'delay')
   at MySqlConnector.Utilities.TimerQueue.Add(Int32 delay, Action action) in C:\projects\mysqlconnector\src\MySqlConnector\Utilities\TimerQueue.cs:line 20
   at MySqlConnector.Protocol.Serialization.StreamByteHandler.<ReadBytesAsync>g__DoReadBytesAsync|6_2(Memory`1 buffer_) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\StreamByteHandler.cs:line 91
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\BufferedByteReader.cs:line 36
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.ReadPacketAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 409
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.DoReadPayloadAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 467
   at MySqlConnector.Protocol.Serialization.StandardPayloadHandler.ReadPayloadAsync(ArraySegmentHolder`1 cache, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\StandardPayloadHandler.cs:line 42
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 750
--- End of stack trace from previous location where exception was thrown ---
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 775
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 226
   at DataSeeder.ApiGatewayAdminDataSeedContributor.SeedAsync(DataSeedContext context) in E:\abp-vue-admin-element-typescript\aspnet-core\services\apigateway\LINGYUN.ApiGateway.HttpApi.Host\DataSeeder\ApiGatewayAdminDataSeedContributor.cs:line 38
   at Volo.Abp.Data.DataSeeder.SeedAsync(DataSeedContext context)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at LINGYUN.ApiGateway.ApiGatewayHttpApiHostModule.<>c__DisplayClass3_0.<<SeedData>b__0>d.MoveNext() in E:\FM_Tech\abp-vue-admin-element-typescript\aspnet-core\services\apigateway\LINGYUN.ApiGateway.HttpApi.Host\ApiGatewayHttpApiHostModule.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.<>c__DisplayClass15_0.<Run>b__0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
```

> > @NiceLisan
> > Now that, I've written the gateway initialization script into the seed data, starting the Gateway management project automatically initializes the gateway data, but you need to combine the **EntityFramework documentation** to ensure that the project database is successfully migrated
> 
> now, i've tried with your latest commitment again.
> i build the projects successfully;
> i configured the database, rabbitmq successfully.
> i seed the database successfully.
> 
> but i still encountered the following errors;
> 
> 1: in the service authserver.host
> 
> ```
> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'platform.abpsettings' doesn't exist
>  
> ```
> 
> 2: in the service \LINGYUN.ApiGateway.HttpApi.Host
> `MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'platform.abppermissiongrants' doesn't exist`
> 
> 3: in the service admin\LINGYUN.BackendAdminApp.Host
> 
> ```
> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'platform.abppermissiongrants' doesn't exist
> ```
> 
> 4: in the service messages\LINGYUN.Abp.MessageService.HttpApi.Host
> 
> ```
> everything works well
>  i can run without any errors.
> ```
> 
> 5: in the service platform\LINGYUN.Platform.HttpApi.Host;
> `it's the only lucky one , i can run without any errors.`
> 
> can you help me to figure out what the hell mistakes had blocked me. sincerely thanks.

**Comment by GerryGe** [comment]
give up
